Mango integration - Init, Deposit, OpenPerpPosition + refactors and anchorization (#26)
* `mint_uxd` works with full mango
- fetching asset price from mango_cache instead of using external oracle
- using fixed crate for numbers as in Mango
- remove oracle from instruction in tests

* Not working WIP
Need to pass more than 8 accounts
else
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 23 out of range for slice of length 8', program/src/processor.rs:1666:24",

* Add more accounts, but not sustainable. Going to do a new devnet testing version

* New script to run tests on devnet, cause that's becoming MESSY that localnet stuff

Still using the same test suit so convenient. Also I put the devnet deployments keep on the repo for now for convenience, that's not cool for later, even on devnet (that program is not live yet)

* Devnet testing script

* Actually no need for a script, can directly use anchor.

* Functionnal mango WIP

* Slippage support + cleanup

* MangoAnchorization
Cause it's prettier, and will make rebase easier. Also easier to think

* Refactored Clean and fitting the computing budget. Many optimization possible still.

* Cleanup + tutti fruti change. WIP but still better to look at

* Working

* misc

* Follow Jet code org.

It was getting wild for me to follow what's going on in that big file.

* Update coin to collateral + some errors improvments

* Update tests, add more Typescript sweetness

* Update tests to use the new solana-usds-client code (it's just a copy, source of truth is there!)

* Working with worse exec price (full slippage) and disabled FILELD AMOUNT check in redeem (to fix)

* enable mint

* Working and accurate UXD minting with fees taken into account

* Working ... But when all put togeter the redeem overflow the computing budget

* remove extra seed calcs

* using the typescript framework

* Updates identity

* Update the typescript framewor and the test accordingly

Misc cleanup

* Update typescript framework to 0.16.0

* Add wsol depository for frontend

* Almost there, STILL issues the withdraw amount being too much

* Working for BTC, still some issues with SOL, might be due to devnet orderbook

* make the id.json the default for anchor

* Working better! Also update tests with leftovers

* Remove provider from Typescript client calls
-update typescript client

Co-authored-by: Bamboozelino <memail>
Co-authored-by: hanako mumei <81144685+2501babe@users.noreply.github.com>